
import React from 'react';
import { MotivationContent } from '../types';

interface QuoteCardProps {
  content: MotivationContent;
  imageUrl: string;
  cardRef: React.RefObject<HTMLDivElement>;
}

const QuoteCard: React.FC<QuoteCardProps> = ({ content, imageUrl, cardRef }) => {
  return (
    <div 
      ref={cardRef}
      className="relative w-full max-w-[400px] aspect-[9/16] overflow-hidden rounded-3xl shadow-2xl bg-slate-900 mx-auto border-4 border-slate-800"
    >
      {/* Background Image */}
      {imageUrl && (
        <img 
          src={imageUrl} 
          alt="Motivation Background" 
          className="absolute inset-0 w-full h-full object-cover"
        />
      )}
      
      {/* Dark Overlay for Readability */}
      <div className="absolute inset-0 bg-gradient-to-t from-black via-black/40 to-transparent"></div>

      {/* Content Overlay */}
      <div className="absolute inset-0 p-8 flex flex-col justify-end text-center">
        {/* Title */}
        <h2 className="text-3xl md:text-4xl font-black text-yellow-400 mb-6 drop-shadow-[0_4px_4px_rgba(0,0,0,0.8)] leading-tight font-['Noto_Sans_Devanagari']">
          {content.title}
        </h2>
        
        <div className="w-24 h-1 bg-yellow-400 mx-auto mb-8 rounded-full shadow-lg"></div>

        {/* Body Text */}
        <p className="text-lg md:text-xl font-bold text-white leading-relaxed drop-shadow-[0_2px_2px_rgba(0,0,0,0.8)] font-['Noto_Sans_Devanagari']">
          {content.body}
        </p>
        
        {/* Branding Placeholder */}
        <div className="mt-12 opacity-40 text-xs tracking-widest font-bold uppercase">
          Generated by Prerna AI
        </div>
      </div>
    </div>
  );
};

export default QuoteCard;
